/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBuzzkillAddressProvider,
  IBuzzkillAddressProviderInterface,
} from "../../interfaces/IBuzzkillAddressProvider";

const _abi = [
  {
    inputs: [],
    name: "buzzkillNFTAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gameConfigAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hiveManagerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "honeyAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "honeyDistributionAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "worldMapAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBuzzkillAddressProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IBuzzkillAddressProviderInterface {
    return new Interface(_abi) as IBuzzkillAddressProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBuzzkillAddressProvider {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBuzzkillAddressProvider;
  }
}
