/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHiveManager,
  IHiveManagerInterface,
} from "../../interfaces/IHiveManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_hiveId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "updateHiveDefense",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_hiveId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "updateHiveProductivity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHiveManager__factory {
  static readonly abi = _abi;
  static createInterface(): IHiveManagerInterface {
    return new Interface(_abi) as IHiveManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHiveManager {
    return new Contract(address, _abi, runner) as unknown as IHiveManager;
  }
}
