/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface GameConfigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Cn"
      | "Cp"
      | "Cs"
      | "amountAttackIncreaseOnLevelUp"
      | "amountBaseProductivityIncreaseOnLevelUp"
      | "amountDefenseIncreaseOnLevelUp"
      | "amountEnergyIncreaseOnLevelUp"
      | "amountForageIncreaseOnLevelUp"
      | "amountHealthIncreaseOnLevelUp"
      | "amountMaxProductivityIncreaseOnLevelUp"
      | "amountToLevelUp"
      | "baseEnergyDeductionAfterRaid"
      | "baseHealthDeductionAfterRaid"
      | "baseHoneyRaidReward"
      | "baseHoneyYield"
      | "baseIncentivePerEpoch"
      | "baseNumberOfForagingQuest"
      | "baseNumberOfRaidQuest"
      | "baseNumberOfRaidSuccessQuest"
      | "baseNumberOfUpgradeQuest"
      | "beeEnergyRefreshInterval"
      | "beeHealthRefreshInterval"
      | "claimTimeInterval"
      | "differenceBetweenLevels"
      | "experienceEarnedAfterForage"
      | "experienceEarnedAfterRaidFailed"
      | "experienceEarnedAfterRaidSuccess"
      | "experienceEarnedAfterUpgrade"
      | "foragePercentage"
      | "honeyYieldConstant"
      | "incentiveEarnAfterRaid"
      | "initialize"
      | "maxQueen"
      | "maxResourcesValue"
      | "maxWorker"
      | "minResourcesValue"
      | "nectarRequiredToClaim"
      | "owner"
      | "raidHoneyFee"
      | "raidSapFee"
      | "renounceOwnership"
      | "resourcesRefreshInterval"
      | "setAmountAttackIncreaseOnLevelUp"
      | "setAmountBaseProductivityIncreaseOnLevelUp"
      | "setAmountDefenseIncreaseOnLevelUp"
      | "setAmountEnergyIncreaseOnLevelUp"
      | "setAmountForageIncreaseOnLevelUp"
      | "setAmountHealthIncreaseOnLevelUp"
      | "setAmountMaxProductivityIncreaseOnLevelUp"
      | "setAmountToLevelUp"
      | "setBaseEnergyDeductionAfterRaid"
      | "setBaseHealthDeductionAfterRaid"
      | "setBaseHoneyRaidReward"
      | "setBaseHoneyYield"
      | "setBaseIncentivePerEpoch"
      | "setBaseNumberOfForagingQuest"
      | "setBaseNumberOfRaidQuest"
      | "setBaseNumberOfRaidSuccessQuest"
      | "setBaseNumberOfUpgradeQuest"
      | "setBeeEnergyRefreshInterval"
      | "setBeeHealthRefreshInterval"
      | "setClaimTimeInterval"
      | "setCn"
      | "setCp"
      | "setCs"
      | "setDifferenceBetweenLevels"
      | "setExperienceEarnedAfterForage"
      | "setExperienceEarnedAfterRaidFailed"
      | "setExperienceEarnedAfterRaidSuccess"
      | "setExperienceEarnedAfterUpgrade"
      | "setForagePercentage"
      | "setHoneyYieldConstant"
      | "setIncentiveEarnAfterRaid"
      | "setMaxQueen"
      | "setMaxResourcesValue"
      | "setMaxWorker"
      | "setMinResourcesValue"
      | "setNectarRequiredToClaim"
      | "setRaidHoneyFee"
      | "setRaidSapFee"
      | "setResourcesRefreshInterval"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmountAttackIncreaseOnLevelUpChanged"
      | "AmountBaseProductivityIncreaseOnLevelUpChanged"
      | "AmountDefenseIncreaseOnLevelUpChanged"
      | "AmountEnergyIncreaseOnLevelUpChanged"
      | "AmountForageIncreaseOnLevelUpChanged"
      | "AmountHealthIncreaseOnLevelUpChanged"
      | "AmountMaxProductivityIncreaseOnLevelUpChanged"
      | "AmountToLevelUpChanged"
      | "BaseEnergyDeductionAfterRaidChanged"
      | "BaseHealthDeductionAfterRaidChanged"
      | "BaseHoneyRaidRewardChanged"
      | "BaseHoneyYieldChanged"
      | "BaseIncentivePerEpochChanged"
      | "BaseNumberOfForagingQuestChanged"
      | "BaseNumberOfRaidQuestChanged"
      | "BaseNumberOfRaidSuccessQuestChanged"
      | "BaseNumberOfUpgradeQuestChanged"
      | "BeeEnergyRefreshIntervalChanged"
      | "BeeHealthRefreshIntervalChanged"
      | "ClaimTimeIntervalChanged"
      | "CnChanged"
      | "CpChanged"
      | "CsChanged"
      | "DifferenceBetweenLevelsChanged"
      | "ExperienceEarnedAfterForageChanged"
      | "ExperienceEarnedAfterRaidFailedChanged"
      | "ExperienceEarnedAfterRaidSuccessChanged"
      | "ExperienceEarnedAfterUpgradeChanged"
      | "ForagePercentageChanged"
      | "HoneyYieldConstantChanged"
      | "IncentiveEarnAfterRaidChanged"
      | "Initialized"
      | "MaxEnergyDeductionValueChanged"
      | "MaxQueenChanged"
      | "MaxResourcesValueChanged"
      | "MaxWorkerChanged"
      | "MinEnergyDeductionValueChanged"
      | "MinResourcesValueChanged"
      | "NectarRequiredToClaimChanged"
      | "OwnershipTransferred"
      | "RaidHoneyFeeChanged"
      | "RaidSapFeeChanged"
      | "ResourcesRefreshIntervalChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "Cn", values?: undefined): string;
  encodeFunctionData(functionFragment: "Cp", values?: undefined): string;
  encodeFunctionData(functionFragment: "Cs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "amountAttackIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountBaseProductivityIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountDefenseIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountEnergyIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountForageIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountHealthIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountMaxProductivityIncreaseOnLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amountToLevelUp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseEnergyDeductionAfterRaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseHealthDeductionAfterRaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseHoneyRaidReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseHoneyYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseIncentivePerEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseNumberOfForagingQuest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseNumberOfRaidQuest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseNumberOfRaidSuccessQuest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseNumberOfUpgradeQuest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beeEnergyRefreshInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beeHealthRefreshInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "differenceBetweenLevels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "experienceEarnedAfterForage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "experienceEarnedAfterRaidFailed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "experienceEarnedAfterRaidSuccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "experienceEarnedAfterUpgrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foragePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "honeyYieldConstant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "incentiveEarnAfterRaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxQueen", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxResourcesValue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxWorker", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minResourcesValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nectarRequiredToClaim",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raidHoneyFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raidSapFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resourcesRefreshInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountAttackIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountBaseProductivityIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountDefenseIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountEnergyIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountForageIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountHealthIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountMaxProductivityIncreaseOnLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmountToLevelUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseEnergyDeductionAfterRaid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseHealthDeductionAfterRaid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseHoneyRaidReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseHoneyYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseIncentivePerEpoch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseNumberOfForagingQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseNumberOfRaidQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseNumberOfRaidSuccessQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseNumberOfUpgradeQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeeEnergyRefreshInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeeHealthRefreshInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimTimeInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setCn", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setCp", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setCs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setDifferenceBetweenLevels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExperienceEarnedAfterForage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExperienceEarnedAfterRaidFailed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExperienceEarnedAfterRaidSuccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExperienceEarnedAfterUpgrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setForagePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHoneyYieldConstant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIncentiveEarnAfterRaid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxQueen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxResourcesValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxWorker",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinResourcesValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNectarRequiredToClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRaidHoneyFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRaidSapFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setResourcesRefreshInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "Cn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Cp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Cs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "amountAttackIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountBaseProductivityIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountDefenseIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountEnergyIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountForageIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountHealthIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountMaxProductivityIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountToLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseEnergyDeductionAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseHealthDeductionAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseHoneyRaidReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseHoneyYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseIncentivePerEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseNumberOfForagingQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseNumberOfRaidQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseNumberOfRaidSuccessQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseNumberOfUpgradeQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beeEnergyRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beeHealthRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "differenceBetweenLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "experienceEarnedAfterForage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "experienceEarnedAfterRaidFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "experienceEarnedAfterRaidSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "experienceEarnedAfterUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "foragePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "honeyYieldConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incentiveEarnAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxQueen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxResourcesValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minResourcesValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nectarRequiredToClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raidHoneyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "raidSapFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resourcesRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountAttackIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountBaseProductivityIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountDefenseIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountEnergyIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountForageIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountHealthIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountMaxProductivityIncreaseOnLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAmountToLevelUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseEnergyDeductionAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseHealthDeductionAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseHoneyRaidReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseHoneyYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseIncentivePerEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseNumberOfForagingQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseNumberOfRaidQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseNumberOfRaidSuccessQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseNumberOfUpgradeQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeeEnergyRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeeHealthRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimTimeInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDifferenceBetweenLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExperienceEarnedAfterForage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExperienceEarnedAfterRaidFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExperienceEarnedAfterRaidSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExperienceEarnedAfterUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForagePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHoneyYieldConstant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIncentiveEarnAfterRaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxQueen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxResourcesValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinResourcesValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNectarRequiredToClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRaidHoneyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRaidSapFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResourcesRefreshInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AmountAttackIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [newAmountAttackIncreaseOnLevelUp: BigNumberish];
  export type OutputTuple = [newAmountAttackIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountAttackIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountBaseProductivityIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [
    newAmountBaseProductivityIncreaseOnLevelUp: BigNumberish
  ];
  export type OutputTuple = [
    newAmountBaseProductivityIncreaseOnLevelUp: bigint
  ];
  export interface OutputObject {
    newAmountBaseProductivityIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountDefenseIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [newAmountDefenseIncreaseOnLevelUp: BigNumberish];
  export type OutputTuple = [newAmountDefenseIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountDefenseIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountEnergyIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [newAmountEnergyIncreaseOnLevelUp: BigNumberish];
  export type OutputTuple = [newAmountEnergyIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountEnergyIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountForageIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [newAmountForageIncreaseOnLevelUp: BigNumberish];
  export type OutputTuple = [newAmountForageIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountForageIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountHealthIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [newAmountHealthIncreaseOnLevelUp: BigNumberish];
  export type OutputTuple = [newAmountHealthIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountHealthIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountMaxProductivityIncreaseOnLevelUpChangedEvent {
  export type InputTuple = [
    newAmountMaxProductivityIncreaseOnLevelUp: BigNumberish
  ];
  export type OutputTuple = [newAmountMaxProductivityIncreaseOnLevelUp: bigint];
  export interface OutputObject {
    newAmountMaxProductivityIncreaseOnLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountToLevelUpChangedEvent {
  export type InputTuple = [newAmountToLevelUp: BigNumberish];
  export type OutputTuple = [newAmountToLevelUp: bigint];
  export interface OutputObject {
    newAmountToLevelUp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseEnergyDeductionAfterRaidChangedEvent {
  export type InputTuple = [newBaseEnergyDeductionAfterRaid: BigNumberish];
  export type OutputTuple = [newBaseEnergyDeductionAfterRaid: bigint];
  export interface OutputObject {
    newBaseEnergyDeductionAfterRaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseHealthDeductionAfterRaidChangedEvent {
  export type InputTuple = [newBaseHealthDeductionAfterRaid: BigNumberish];
  export type OutputTuple = [newBaseHealthDeductionAfterRaid: bigint];
  export interface OutputObject {
    newBaseHealthDeductionAfterRaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseHoneyRaidRewardChangedEvent {
  export type InputTuple = [newBaseHoneyRaidReward: BigNumberish];
  export type OutputTuple = [newBaseHoneyRaidReward: bigint];
  export interface OutputObject {
    newBaseHoneyRaidReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseHoneyYieldChangedEvent {
  export type InputTuple = [newBaseHoneyYield: BigNumberish];
  export type OutputTuple = [newBaseHoneyYield: bigint];
  export interface OutputObject {
    newBaseHoneyYield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseIncentivePerEpochChangedEvent {
  export type InputTuple = [newBaseIncentivePerEpoch: BigNumberish];
  export type OutputTuple = [newBaseIncentivePerEpoch: bigint];
  export interface OutputObject {
    newBaseIncentivePerEpoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseNumberOfForagingQuestChangedEvent {
  export type InputTuple = [newBaseNumberOfForagingQuest: BigNumberish];
  export type OutputTuple = [newBaseNumberOfForagingQuest: bigint];
  export interface OutputObject {
    newBaseNumberOfForagingQuest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseNumberOfRaidQuestChangedEvent {
  export type InputTuple = [newBaseNumberOfRaidQuest: BigNumberish];
  export type OutputTuple = [newBaseNumberOfRaidQuest: bigint];
  export interface OutputObject {
    newBaseNumberOfRaidQuest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseNumberOfRaidSuccessQuestChangedEvent {
  export type InputTuple = [newBaseNumberOfRaidSuccessQuest: BigNumberish];
  export type OutputTuple = [newBaseNumberOfRaidSuccessQuest: bigint];
  export interface OutputObject {
    newBaseNumberOfRaidSuccessQuest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseNumberOfUpgradeQuestChangedEvent {
  export type InputTuple = [newBaseNumberOfUpgradeQuest: BigNumberish];
  export type OutputTuple = [newBaseNumberOfUpgradeQuest: bigint];
  export interface OutputObject {
    newBaseNumberOfUpgradeQuest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeeEnergyRefreshIntervalChangedEvent {
  export type InputTuple = [newBeeEnergyRefreshInterval: BigNumberish];
  export type OutputTuple = [newBeeEnergyRefreshInterval: bigint];
  export interface OutputObject {
    newBeeEnergyRefreshInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeeHealthRefreshIntervalChangedEvent {
  export type InputTuple = [newBeeHealthRefreshInterval: BigNumberish];
  export type OutputTuple = [newBeeHealthRefreshInterval: bigint];
  export interface OutputObject {
    newBeeHealthRefreshInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimTimeIntervalChangedEvent {
  export type InputTuple = [newClaimTimeInterval: BigNumberish];
  export type OutputTuple = [newClaimTimeInterval: bigint];
  export interface OutputObject {
    newClaimTimeInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CnChangedEvent {
  export type InputTuple = [newCn: BigNumberish];
  export type OutputTuple = [newCn: bigint];
  export interface OutputObject {
    newCn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CpChangedEvent {
  export type InputTuple = [newCp: BigNumberish];
  export type OutputTuple = [newCp: bigint];
  export interface OutputObject {
    newCp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CsChangedEvent {
  export type InputTuple = [newCs: BigNumberish];
  export type OutputTuple = [newCs: bigint];
  export interface OutputObject {
    newCs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DifferenceBetweenLevelsChangedEvent {
  export type InputTuple = [newDifferenceBetweenLevels: BigNumberish];
  export type OutputTuple = [newDifferenceBetweenLevels: bigint];
  export interface OutputObject {
    newDifferenceBetweenLevels: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExperienceEarnedAfterForageChangedEvent {
  export type InputTuple = [newExperienceEarnedAfterForage: BigNumberish];
  export type OutputTuple = [newExperienceEarnedAfterForage: bigint];
  export interface OutputObject {
    newExperienceEarnedAfterForage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExperienceEarnedAfterRaidFailedChangedEvent {
  export type InputTuple = [newExperienceEarnedAfterRaidFailed: BigNumberish];
  export type OutputTuple = [newExperienceEarnedAfterRaidFailed: bigint];
  export interface OutputObject {
    newExperienceEarnedAfterRaidFailed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExperienceEarnedAfterRaidSuccessChangedEvent {
  export type InputTuple = [newExperienceEarnedAfterRaidSuccess: BigNumberish];
  export type OutputTuple = [newExperienceEarnedAfterRaidSuccess: bigint];
  export interface OutputObject {
    newExperienceEarnedAfterRaidSuccess: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExperienceEarnedAfterUpgradeChangedEvent {
  export type InputTuple = [newExperienceEarnedAfterUpgrade: BigNumberish];
  export type OutputTuple = [newExperienceEarnedAfterUpgrade: bigint];
  export interface OutputObject {
    newExperienceEarnedAfterUpgrade: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForagePercentageChangedEvent {
  export type InputTuple = [newForagePercentage: BigNumberish];
  export type OutputTuple = [newForagePercentage: bigint];
  export interface OutputObject {
    newForagePercentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HoneyYieldConstantChangedEvent {
  export type InputTuple = [newHoneyYieldConstant: BigNumberish];
  export type OutputTuple = [newHoneyYieldConstant: bigint];
  export interface OutputObject {
    newHoneyYieldConstant: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncentiveEarnAfterRaidChangedEvent {
  export type InputTuple = [newIncentiveEarnAfterRaid: BigNumberish];
  export type OutputTuple = [newIncentiveEarnAfterRaid: bigint];
  export interface OutputObject {
    newIncentiveEarnAfterRaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxEnergyDeductionValueChangedEvent {
  export type InputTuple = [newMaxEnergyDeductionValue: BigNumberish];
  export type OutputTuple = [newMaxEnergyDeductionValue: bigint];
  export interface OutputObject {
    newMaxEnergyDeductionValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxQueenChangedEvent {
  export type InputTuple = [newMaxQueen: BigNumberish];
  export type OutputTuple = [newMaxQueen: bigint];
  export interface OutputObject {
    newMaxQueen: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxResourcesValueChangedEvent {
  export type InputTuple = [newMaxResourcesValue: BigNumberish];
  export type OutputTuple = [newMaxResourcesValue: bigint];
  export interface OutputObject {
    newMaxResourcesValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxWorkerChangedEvent {
  export type InputTuple = [newMaxWorker: BigNumberish];
  export type OutputTuple = [newMaxWorker: bigint];
  export interface OutputObject {
    newMaxWorker: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinEnergyDeductionValueChangedEvent {
  export type InputTuple = [newMinEnergyDeductionValue: BigNumberish];
  export type OutputTuple = [newMinEnergyDeductionValue: bigint];
  export interface OutputObject {
    newMinEnergyDeductionValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinResourcesValueChangedEvent {
  export type InputTuple = [newMinResourcesValue: BigNumberish];
  export type OutputTuple = [newMinResourcesValue: bigint];
  export interface OutputObject {
    newMinResourcesValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NectarRequiredToClaimChangedEvent {
  export type InputTuple = [newNectarRequiredToClaim: BigNumberish];
  export type OutputTuple = [newNectarRequiredToClaim: bigint];
  export interface OutputObject {
    newNectarRequiredToClaim: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaidHoneyFeeChangedEvent {
  export type InputTuple = [newRaidHoneyFee: BigNumberish];
  export type OutputTuple = [newRaidHoneyFee: bigint];
  export interface OutputObject {
    newRaidHoneyFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaidSapFeeChangedEvent {
  export type InputTuple = [newRaidSapFee: BigNumberish];
  export type OutputTuple = [newRaidSapFee: bigint];
  export interface OutputObject {
    newRaidSapFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResourcesRefreshIntervalChangedEvent {
  export type InputTuple = [newResourcesRefreshInterval: BigNumberish];
  export type OutputTuple = [newResourcesRefreshInterval: bigint];
  export interface OutputObject {
    newResourcesRefreshInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameConfig extends BaseContract {
  connect(runner?: ContractRunner | null): GameConfig;
  waitForDeployment(): Promise<this>;

  interface: GameConfigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Cn: TypedContractMethod<[], [bigint], "view">;

  Cp: TypedContractMethod<[], [bigint], "view">;

  Cs: TypedContractMethod<[], [bigint], "view">;

  amountAttackIncreaseOnLevelUp: TypedContractMethod<[], [bigint], "view">;

  amountBaseProductivityIncreaseOnLevelUp: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  amountDefenseIncreaseOnLevelUp: TypedContractMethod<[], [bigint], "view">;

  amountEnergyIncreaseOnLevelUp: TypedContractMethod<[], [bigint], "view">;

  amountForageIncreaseOnLevelUp: TypedContractMethod<[], [bigint], "view">;

  amountHealthIncreaseOnLevelUp: TypedContractMethod<[], [bigint], "view">;

  amountMaxProductivityIncreaseOnLevelUp: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  amountToLevelUp: TypedContractMethod<[], [bigint], "view">;

  baseEnergyDeductionAfterRaid: TypedContractMethod<[], [bigint], "view">;

  baseHealthDeductionAfterRaid: TypedContractMethod<[], [bigint], "view">;

  baseHoneyRaidReward: TypedContractMethod<[], [bigint], "view">;

  baseHoneyYield: TypedContractMethod<[], [bigint], "view">;

  baseIncentivePerEpoch: TypedContractMethod<[], [bigint], "view">;

  baseNumberOfForagingQuest: TypedContractMethod<[], [bigint], "view">;

  baseNumberOfRaidQuest: TypedContractMethod<[], [bigint], "view">;

  baseNumberOfRaidSuccessQuest: TypedContractMethod<[], [bigint], "view">;

  baseNumberOfUpgradeQuest: TypedContractMethod<[], [bigint], "view">;

  beeEnergyRefreshInterval: TypedContractMethod<[], [bigint], "view">;

  beeHealthRefreshInterval: TypedContractMethod<[], [bigint], "view">;

  claimTimeInterval: TypedContractMethod<[], [bigint], "view">;

  differenceBetweenLevels: TypedContractMethod<[], [bigint], "view">;

  experienceEarnedAfterForage: TypedContractMethod<[], [bigint], "view">;

  experienceEarnedAfterRaidFailed: TypedContractMethod<[], [bigint], "view">;

  experienceEarnedAfterRaidSuccess: TypedContractMethod<[], [bigint], "view">;

  experienceEarnedAfterUpgrade: TypedContractMethod<[], [bigint], "view">;

  foragePercentage: TypedContractMethod<[], [bigint], "view">;

  honeyYieldConstant: TypedContractMethod<[], [bigint], "view">;

  incentiveEarnAfterRaid: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  maxQueen: TypedContractMethod<[], [bigint], "view">;

  maxResourcesValue: TypedContractMethod<[], [bigint], "view">;

  maxWorker: TypedContractMethod<[], [bigint], "view">;

  minResourcesValue: TypedContractMethod<[], [bigint], "view">;

  nectarRequiredToClaim: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raidHoneyFee: TypedContractMethod<[], [bigint], "view">;

  raidSapFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resourcesRefreshInterval: TypedContractMethod<[], [bigint], "view">;

  setAmountAttackIncreaseOnLevelUp: TypedContractMethod<
    [_amountAttackIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountBaseProductivityIncreaseOnLevelUp: TypedContractMethod<
    [_amountBaseProductivityIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountDefenseIncreaseOnLevelUp: TypedContractMethod<
    [_amountDefenseIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountEnergyIncreaseOnLevelUp: TypedContractMethod<
    [_amountEnergyIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountForageIncreaseOnLevelUp: TypedContractMethod<
    [_amountForageIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountHealthIncreaseOnLevelUp: TypedContractMethod<
    [_amountHealthIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountMaxProductivityIncreaseOnLevelUp: TypedContractMethod<
    [_amountMaxProductivityIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAmountToLevelUp: TypedContractMethod<
    [_amountToLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseEnergyDeductionAfterRaid: TypedContractMethod<
    [_baseEnergyDeductionAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseHealthDeductionAfterRaid: TypedContractMethod<
    [_baseHealthDeductionAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseHoneyRaidReward: TypedContractMethod<
    [_baseHoneyRaidReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseHoneyYield: TypedContractMethod<
    [_baseHoneyYield: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseIncentivePerEpoch: TypedContractMethod<
    [_baseIncentivePerEpoch: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseNumberOfForagingQuest: TypedContractMethod<
    [_baseNumberOfForagingQuest: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseNumberOfRaidQuest: TypedContractMethod<
    [_baseNumberOfRaidQuest: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseNumberOfRaidSuccessQuest: TypedContractMethod<
    [_baseNumberOfRaidSuccessQuest: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseNumberOfUpgradeQuest: TypedContractMethod<
    [_baseNumberOfUpgradeQuest: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBeeEnergyRefreshInterval: TypedContractMethod<
    [_beeEnergyRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBeeHealthRefreshInterval: TypedContractMethod<
    [_beeHealthRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  setClaimTimeInterval: TypedContractMethod<
    [_claimTimeInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCn: TypedContractMethod<[_Cn: BigNumberish], [void], "nonpayable">;

  setCp: TypedContractMethod<[_Cp: BigNumberish], [void], "nonpayable">;

  setCs: TypedContractMethod<[_Cs: BigNumberish], [void], "nonpayable">;

  setDifferenceBetweenLevels: TypedContractMethod<
    [_differenceBetweenLevels: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExperienceEarnedAfterForage: TypedContractMethod<
    [_experienceEarnedAfterForage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExperienceEarnedAfterRaidFailed: TypedContractMethod<
    [_experienceEarnedAfterRaidFailed: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExperienceEarnedAfterRaidSuccess: TypedContractMethod<
    [_experienceEarnedAfterRaidSuccess: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExperienceEarnedAfterUpgrade: TypedContractMethod<
    [_experienceEarnedAfterUpgrade: BigNumberish],
    [void],
    "nonpayable"
  >;

  setForagePercentage: TypedContractMethod<
    [_foragePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHoneyYieldConstant: TypedContractMethod<
    [_honeyYieldConstant: BigNumberish],
    [void],
    "nonpayable"
  >;

  setIncentiveEarnAfterRaid: TypedContractMethod<
    [_incentiveEarnAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxQueen: TypedContractMethod<
    [_maxQueen: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxResourcesValue: TypedContractMethod<
    [_maxResourcesValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxWorker: TypedContractMethod<
    [_maxWorker: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinResourcesValue: TypedContractMethod<
    [_minResourcesValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  setNectarRequiredToClaim: TypedContractMethod<
    [_nectarRequiredToClaim: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRaidHoneyFee: TypedContractMethod<
    [_raidHoneyFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRaidSapFee: TypedContractMethod<
    [_raidSapFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setResourcesRefreshInterval: TypedContractMethod<
    [_resourcesRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "Cn"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "Cp"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "Cs"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountAttackIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountBaseProductivityIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountDefenseIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountEnergyIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountForageIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountHealthIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountMaxProductivityIncreaseOnLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amountToLevelUp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseEnergyDeductionAfterRaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseHealthDeductionAfterRaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseHoneyRaidReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseHoneyYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseIncentivePerEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseNumberOfForagingQuest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseNumberOfRaidQuest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseNumberOfRaidSuccessQuest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseNumberOfUpgradeQuest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beeEnergyRefreshInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beeHealthRefreshInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimTimeInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "differenceBetweenLevels"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "experienceEarnedAfterForage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "experienceEarnedAfterRaidFailed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "experienceEarnedAfterRaidSuccess"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "experienceEarnedAfterUpgrade"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "foragePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "honeyYieldConstant"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "incentiveEarnAfterRaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "maxQueen"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxResourcesValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWorker"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minResourcesValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nectarRequiredToClaim"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raidHoneyFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raidSapFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resourcesRefreshInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAmountAttackIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountAttackIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountBaseProductivityIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountBaseProductivityIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountDefenseIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountDefenseIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountEnergyIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountEnergyIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountForageIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountForageIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountHealthIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountHealthIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountMaxProductivityIncreaseOnLevelUp"
  ): TypedContractMethod<
    [_amountMaxProductivityIncreaseOnLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmountToLevelUp"
  ): TypedContractMethod<
    [_amountToLevelUp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseEnergyDeductionAfterRaid"
  ): TypedContractMethod<
    [_baseEnergyDeductionAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseHealthDeductionAfterRaid"
  ): TypedContractMethod<
    [_baseHealthDeductionAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseHoneyRaidReward"
  ): TypedContractMethod<
    [_baseHoneyRaidReward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseHoneyYield"
  ): TypedContractMethod<[_baseHoneyYield: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBaseIncentivePerEpoch"
  ): TypedContractMethod<
    [_baseIncentivePerEpoch: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseNumberOfForagingQuest"
  ): TypedContractMethod<
    [_baseNumberOfForagingQuest: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseNumberOfRaidQuest"
  ): TypedContractMethod<
    [_baseNumberOfRaidQuest: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseNumberOfRaidSuccessQuest"
  ): TypedContractMethod<
    [_baseNumberOfRaidSuccessQuest: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseNumberOfUpgradeQuest"
  ): TypedContractMethod<
    [_baseNumberOfUpgradeQuest: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBeeEnergyRefreshInterval"
  ): TypedContractMethod<
    [_beeEnergyRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBeeHealthRefreshInterval"
  ): TypedContractMethod<
    [_beeHealthRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setClaimTimeInterval"
  ): TypedContractMethod<
    [_claimTimeInterval: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCn"
  ): TypedContractMethod<[_Cn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCp"
  ): TypedContractMethod<[_Cp: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCs"
  ): TypedContractMethod<[_Cs: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDifferenceBetweenLevels"
  ): TypedContractMethod<
    [_differenceBetweenLevels: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExperienceEarnedAfterForage"
  ): TypedContractMethod<
    [_experienceEarnedAfterForage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExperienceEarnedAfterRaidFailed"
  ): TypedContractMethod<
    [_experienceEarnedAfterRaidFailed: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExperienceEarnedAfterRaidSuccess"
  ): TypedContractMethod<
    [_experienceEarnedAfterRaidSuccess: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExperienceEarnedAfterUpgrade"
  ): TypedContractMethod<
    [_experienceEarnedAfterUpgrade: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setForagePercentage"
  ): TypedContractMethod<
    [_foragePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHoneyYieldConstant"
  ): TypedContractMethod<
    [_honeyYieldConstant: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIncentiveEarnAfterRaid"
  ): TypedContractMethod<
    [_incentiveEarnAfterRaid: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxQueen"
  ): TypedContractMethod<[_maxQueen: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxResourcesValue"
  ): TypedContractMethod<
    [_maxResourcesValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxWorker"
  ): TypedContractMethod<[_maxWorker: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinResourcesValue"
  ): TypedContractMethod<
    [_minResourcesValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNectarRequiredToClaim"
  ): TypedContractMethod<
    [_nectarRequiredToClaim: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRaidHoneyFee"
  ): TypedContractMethod<[_raidHoneyFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRaidSapFee"
  ): TypedContractMethod<[_raidSapFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setResourcesRefreshInterval"
  ): TypedContractMethod<
    [_resourcesRefreshInterval: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AmountAttackIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountAttackIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountAttackIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountAttackIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountBaseProductivityIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountBaseProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountDefenseIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountDefenseIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountDefenseIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountDefenseIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountEnergyIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountEnergyIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountEnergyIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountEnergyIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountForageIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountForageIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountForageIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountForageIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountHealthIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountHealthIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountHealthIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountHealthIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountMaxProductivityIncreaseOnLevelUpChanged"
  ): TypedContractEvent<
    AmountMaxProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
    AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
    AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "AmountToLevelUpChanged"
  ): TypedContractEvent<
    AmountToLevelUpChangedEvent.InputTuple,
    AmountToLevelUpChangedEvent.OutputTuple,
    AmountToLevelUpChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseEnergyDeductionAfterRaidChanged"
  ): TypedContractEvent<
    BaseEnergyDeductionAfterRaidChangedEvent.InputTuple,
    BaseEnergyDeductionAfterRaidChangedEvent.OutputTuple,
    BaseEnergyDeductionAfterRaidChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseHealthDeductionAfterRaidChanged"
  ): TypedContractEvent<
    BaseHealthDeductionAfterRaidChangedEvent.InputTuple,
    BaseHealthDeductionAfterRaidChangedEvent.OutputTuple,
    BaseHealthDeductionAfterRaidChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseHoneyRaidRewardChanged"
  ): TypedContractEvent<
    BaseHoneyRaidRewardChangedEvent.InputTuple,
    BaseHoneyRaidRewardChangedEvent.OutputTuple,
    BaseHoneyRaidRewardChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseHoneyYieldChanged"
  ): TypedContractEvent<
    BaseHoneyYieldChangedEvent.InputTuple,
    BaseHoneyYieldChangedEvent.OutputTuple,
    BaseHoneyYieldChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseIncentivePerEpochChanged"
  ): TypedContractEvent<
    BaseIncentivePerEpochChangedEvent.InputTuple,
    BaseIncentivePerEpochChangedEvent.OutputTuple,
    BaseIncentivePerEpochChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseNumberOfForagingQuestChanged"
  ): TypedContractEvent<
    BaseNumberOfForagingQuestChangedEvent.InputTuple,
    BaseNumberOfForagingQuestChangedEvent.OutputTuple,
    BaseNumberOfForagingQuestChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseNumberOfRaidQuestChanged"
  ): TypedContractEvent<
    BaseNumberOfRaidQuestChangedEvent.InputTuple,
    BaseNumberOfRaidQuestChangedEvent.OutputTuple,
    BaseNumberOfRaidQuestChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseNumberOfRaidSuccessQuestChanged"
  ): TypedContractEvent<
    BaseNumberOfRaidSuccessQuestChangedEvent.InputTuple,
    BaseNumberOfRaidSuccessQuestChangedEvent.OutputTuple,
    BaseNumberOfRaidSuccessQuestChangedEvent.OutputObject
  >;
  getEvent(
    key: "BaseNumberOfUpgradeQuestChanged"
  ): TypedContractEvent<
    BaseNumberOfUpgradeQuestChangedEvent.InputTuple,
    BaseNumberOfUpgradeQuestChangedEvent.OutputTuple,
    BaseNumberOfUpgradeQuestChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeeEnergyRefreshIntervalChanged"
  ): TypedContractEvent<
    BeeEnergyRefreshIntervalChangedEvent.InputTuple,
    BeeEnergyRefreshIntervalChangedEvent.OutputTuple,
    BeeEnergyRefreshIntervalChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeeHealthRefreshIntervalChanged"
  ): TypedContractEvent<
    BeeHealthRefreshIntervalChangedEvent.InputTuple,
    BeeHealthRefreshIntervalChangedEvent.OutputTuple,
    BeeHealthRefreshIntervalChangedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimTimeIntervalChanged"
  ): TypedContractEvent<
    ClaimTimeIntervalChangedEvent.InputTuple,
    ClaimTimeIntervalChangedEvent.OutputTuple,
    ClaimTimeIntervalChangedEvent.OutputObject
  >;
  getEvent(
    key: "CnChanged"
  ): TypedContractEvent<
    CnChangedEvent.InputTuple,
    CnChangedEvent.OutputTuple,
    CnChangedEvent.OutputObject
  >;
  getEvent(
    key: "CpChanged"
  ): TypedContractEvent<
    CpChangedEvent.InputTuple,
    CpChangedEvent.OutputTuple,
    CpChangedEvent.OutputObject
  >;
  getEvent(
    key: "CsChanged"
  ): TypedContractEvent<
    CsChangedEvent.InputTuple,
    CsChangedEvent.OutputTuple,
    CsChangedEvent.OutputObject
  >;
  getEvent(
    key: "DifferenceBetweenLevelsChanged"
  ): TypedContractEvent<
    DifferenceBetweenLevelsChangedEvent.InputTuple,
    DifferenceBetweenLevelsChangedEvent.OutputTuple,
    DifferenceBetweenLevelsChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExperienceEarnedAfterForageChanged"
  ): TypedContractEvent<
    ExperienceEarnedAfterForageChangedEvent.InputTuple,
    ExperienceEarnedAfterForageChangedEvent.OutputTuple,
    ExperienceEarnedAfterForageChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExperienceEarnedAfterRaidFailedChanged"
  ): TypedContractEvent<
    ExperienceEarnedAfterRaidFailedChangedEvent.InputTuple,
    ExperienceEarnedAfterRaidFailedChangedEvent.OutputTuple,
    ExperienceEarnedAfterRaidFailedChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExperienceEarnedAfterRaidSuccessChanged"
  ): TypedContractEvent<
    ExperienceEarnedAfterRaidSuccessChangedEvent.InputTuple,
    ExperienceEarnedAfterRaidSuccessChangedEvent.OutputTuple,
    ExperienceEarnedAfterRaidSuccessChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExperienceEarnedAfterUpgradeChanged"
  ): TypedContractEvent<
    ExperienceEarnedAfterUpgradeChangedEvent.InputTuple,
    ExperienceEarnedAfterUpgradeChangedEvent.OutputTuple,
    ExperienceEarnedAfterUpgradeChangedEvent.OutputObject
  >;
  getEvent(
    key: "ForagePercentageChanged"
  ): TypedContractEvent<
    ForagePercentageChangedEvent.InputTuple,
    ForagePercentageChangedEvent.OutputTuple,
    ForagePercentageChangedEvent.OutputObject
  >;
  getEvent(
    key: "HoneyYieldConstantChanged"
  ): TypedContractEvent<
    HoneyYieldConstantChangedEvent.InputTuple,
    HoneyYieldConstantChangedEvent.OutputTuple,
    HoneyYieldConstantChangedEvent.OutputObject
  >;
  getEvent(
    key: "IncentiveEarnAfterRaidChanged"
  ): TypedContractEvent<
    IncentiveEarnAfterRaidChangedEvent.InputTuple,
    IncentiveEarnAfterRaidChangedEvent.OutputTuple,
    IncentiveEarnAfterRaidChangedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MaxEnergyDeductionValueChanged"
  ): TypedContractEvent<
    MaxEnergyDeductionValueChangedEvent.InputTuple,
    MaxEnergyDeductionValueChangedEvent.OutputTuple,
    MaxEnergyDeductionValueChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxQueenChanged"
  ): TypedContractEvent<
    MaxQueenChangedEvent.InputTuple,
    MaxQueenChangedEvent.OutputTuple,
    MaxQueenChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxResourcesValueChanged"
  ): TypedContractEvent<
    MaxResourcesValueChangedEvent.InputTuple,
    MaxResourcesValueChangedEvent.OutputTuple,
    MaxResourcesValueChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxWorkerChanged"
  ): TypedContractEvent<
    MaxWorkerChangedEvent.InputTuple,
    MaxWorkerChangedEvent.OutputTuple,
    MaxWorkerChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinEnergyDeductionValueChanged"
  ): TypedContractEvent<
    MinEnergyDeductionValueChangedEvent.InputTuple,
    MinEnergyDeductionValueChangedEvent.OutputTuple,
    MinEnergyDeductionValueChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinResourcesValueChanged"
  ): TypedContractEvent<
    MinResourcesValueChangedEvent.InputTuple,
    MinResourcesValueChangedEvent.OutputTuple,
    MinResourcesValueChangedEvent.OutputObject
  >;
  getEvent(
    key: "NectarRequiredToClaimChanged"
  ): TypedContractEvent<
    NectarRequiredToClaimChangedEvent.InputTuple,
    NectarRequiredToClaimChangedEvent.OutputTuple,
    NectarRequiredToClaimChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RaidHoneyFeeChanged"
  ): TypedContractEvent<
    RaidHoneyFeeChangedEvent.InputTuple,
    RaidHoneyFeeChangedEvent.OutputTuple,
    RaidHoneyFeeChangedEvent.OutputObject
  >;
  getEvent(
    key: "RaidSapFeeChanged"
  ): TypedContractEvent<
    RaidSapFeeChangedEvent.InputTuple,
    RaidSapFeeChangedEvent.OutputTuple,
    RaidSapFeeChangedEvent.OutputObject
  >;
  getEvent(
    key: "ResourcesRefreshIntervalChanged"
  ): TypedContractEvent<
    ResourcesRefreshIntervalChangedEvent.InputTuple,
    ResourcesRefreshIntervalChangedEvent.OutputTuple,
    ResourcesRefreshIntervalChangedEvent.OutputObject
  >;

  filters: {
    "AmountAttackIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountAttackIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountAttackIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountAttackIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountAttackIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountAttackIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountAttackIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountAttackIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountBaseProductivityIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountBaseProductivityIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountBaseProductivityIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountDefenseIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountDefenseIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountDefenseIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountDefenseIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountDefenseIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountDefenseIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountDefenseIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountDefenseIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountEnergyIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountEnergyIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountEnergyIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountEnergyIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountEnergyIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountEnergyIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountEnergyIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountEnergyIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountForageIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountForageIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountForageIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountForageIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountForageIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountForageIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountForageIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountForageIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountHealthIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountHealthIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountHealthIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountHealthIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountHealthIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountHealthIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountHealthIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountHealthIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountMaxProductivityIncreaseOnLevelUpChanged(uint256)": TypedContractEvent<
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputObject
    >;
    AmountMaxProductivityIncreaseOnLevelUpChanged: TypedContractEvent<
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.InputTuple,
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputTuple,
      AmountMaxProductivityIncreaseOnLevelUpChangedEvent.OutputObject
    >;

    "AmountToLevelUpChanged(uint256)": TypedContractEvent<
      AmountToLevelUpChangedEvent.InputTuple,
      AmountToLevelUpChangedEvent.OutputTuple,
      AmountToLevelUpChangedEvent.OutputObject
    >;
    AmountToLevelUpChanged: TypedContractEvent<
      AmountToLevelUpChangedEvent.InputTuple,
      AmountToLevelUpChangedEvent.OutputTuple,
      AmountToLevelUpChangedEvent.OutputObject
    >;

    "BaseEnergyDeductionAfterRaidChanged(uint256)": TypedContractEvent<
      BaseEnergyDeductionAfterRaidChangedEvent.InputTuple,
      BaseEnergyDeductionAfterRaidChangedEvent.OutputTuple,
      BaseEnergyDeductionAfterRaidChangedEvent.OutputObject
    >;
    BaseEnergyDeductionAfterRaidChanged: TypedContractEvent<
      BaseEnergyDeductionAfterRaidChangedEvent.InputTuple,
      BaseEnergyDeductionAfterRaidChangedEvent.OutputTuple,
      BaseEnergyDeductionAfterRaidChangedEvent.OutputObject
    >;

    "BaseHealthDeductionAfterRaidChanged(uint256)": TypedContractEvent<
      BaseHealthDeductionAfterRaidChangedEvent.InputTuple,
      BaseHealthDeductionAfterRaidChangedEvent.OutputTuple,
      BaseHealthDeductionAfterRaidChangedEvent.OutputObject
    >;
    BaseHealthDeductionAfterRaidChanged: TypedContractEvent<
      BaseHealthDeductionAfterRaidChangedEvent.InputTuple,
      BaseHealthDeductionAfterRaidChangedEvent.OutputTuple,
      BaseHealthDeductionAfterRaidChangedEvent.OutputObject
    >;

    "BaseHoneyRaidRewardChanged(uint256)": TypedContractEvent<
      BaseHoneyRaidRewardChangedEvent.InputTuple,
      BaseHoneyRaidRewardChangedEvent.OutputTuple,
      BaseHoneyRaidRewardChangedEvent.OutputObject
    >;
    BaseHoneyRaidRewardChanged: TypedContractEvent<
      BaseHoneyRaidRewardChangedEvent.InputTuple,
      BaseHoneyRaidRewardChangedEvent.OutputTuple,
      BaseHoneyRaidRewardChangedEvent.OutputObject
    >;

    "BaseHoneyYieldChanged(uint256)": TypedContractEvent<
      BaseHoneyYieldChangedEvent.InputTuple,
      BaseHoneyYieldChangedEvent.OutputTuple,
      BaseHoneyYieldChangedEvent.OutputObject
    >;
    BaseHoneyYieldChanged: TypedContractEvent<
      BaseHoneyYieldChangedEvent.InputTuple,
      BaseHoneyYieldChangedEvent.OutputTuple,
      BaseHoneyYieldChangedEvent.OutputObject
    >;

    "BaseIncentivePerEpochChanged(uint256)": TypedContractEvent<
      BaseIncentivePerEpochChangedEvent.InputTuple,
      BaseIncentivePerEpochChangedEvent.OutputTuple,
      BaseIncentivePerEpochChangedEvent.OutputObject
    >;
    BaseIncentivePerEpochChanged: TypedContractEvent<
      BaseIncentivePerEpochChangedEvent.InputTuple,
      BaseIncentivePerEpochChangedEvent.OutputTuple,
      BaseIncentivePerEpochChangedEvent.OutputObject
    >;

    "BaseNumberOfForagingQuestChanged(uint256)": TypedContractEvent<
      BaseNumberOfForagingQuestChangedEvent.InputTuple,
      BaseNumberOfForagingQuestChangedEvent.OutputTuple,
      BaseNumberOfForagingQuestChangedEvent.OutputObject
    >;
    BaseNumberOfForagingQuestChanged: TypedContractEvent<
      BaseNumberOfForagingQuestChangedEvent.InputTuple,
      BaseNumberOfForagingQuestChangedEvent.OutputTuple,
      BaseNumberOfForagingQuestChangedEvent.OutputObject
    >;

    "BaseNumberOfRaidQuestChanged(uint256)": TypedContractEvent<
      BaseNumberOfRaidQuestChangedEvent.InputTuple,
      BaseNumberOfRaidQuestChangedEvent.OutputTuple,
      BaseNumberOfRaidQuestChangedEvent.OutputObject
    >;
    BaseNumberOfRaidQuestChanged: TypedContractEvent<
      BaseNumberOfRaidQuestChangedEvent.InputTuple,
      BaseNumberOfRaidQuestChangedEvent.OutputTuple,
      BaseNumberOfRaidQuestChangedEvent.OutputObject
    >;

    "BaseNumberOfRaidSuccessQuestChanged(uint256)": TypedContractEvent<
      BaseNumberOfRaidSuccessQuestChangedEvent.InputTuple,
      BaseNumberOfRaidSuccessQuestChangedEvent.OutputTuple,
      BaseNumberOfRaidSuccessQuestChangedEvent.OutputObject
    >;
    BaseNumberOfRaidSuccessQuestChanged: TypedContractEvent<
      BaseNumberOfRaidSuccessQuestChangedEvent.InputTuple,
      BaseNumberOfRaidSuccessQuestChangedEvent.OutputTuple,
      BaseNumberOfRaidSuccessQuestChangedEvent.OutputObject
    >;

    "BaseNumberOfUpgradeQuestChanged(uint256)": TypedContractEvent<
      BaseNumberOfUpgradeQuestChangedEvent.InputTuple,
      BaseNumberOfUpgradeQuestChangedEvent.OutputTuple,
      BaseNumberOfUpgradeQuestChangedEvent.OutputObject
    >;
    BaseNumberOfUpgradeQuestChanged: TypedContractEvent<
      BaseNumberOfUpgradeQuestChangedEvent.InputTuple,
      BaseNumberOfUpgradeQuestChangedEvent.OutputTuple,
      BaseNumberOfUpgradeQuestChangedEvent.OutputObject
    >;

    "BeeEnergyRefreshIntervalChanged(uint256)": TypedContractEvent<
      BeeEnergyRefreshIntervalChangedEvent.InputTuple,
      BeeEnergyRefreshIntervalChangedEvent.OutputTuple,
      BeeEnergyRefreshIntervalChangedEvent.OutputObject
    >;
    BeeEnergyRefreshIntervalChanged: TypedContractEvent<
      BeeEnergyRefreshIntervalChangedEvent.InputTuple,
      BeeEnergyRefreshIntervalChangedEvent.OutputTuple,
      BeeEnergyRefreshIntervalChangedEvent.OutputObject
    >;

    "BeeHealthRefreshIntervalChanged(uint256)": TypedContractEvent<
      BeeHealthRefreshIntervalChangedEvent.InputTuple,
      BeeHealthRefreshIntervalChangedEvent.OutputTuple,
      BeeHealthRefreshIntervalChangedEvent.OutputObject
    >;
    BeeHealthRefreshIntervalChanged: TypedContractEvent<
      BeeHealthRefreshIntervalChangedEvent.InputTuple,
      BeeHealthRefreshIntervalChangedEvent.OutputTuple,
      BeeHealthRefreshIntervalChangedEvent.OutputObject
    >;

    "ClaimTimeIntervalChanged(uint256)": TypedContractEvent<
      ClaimTimeIntervalChangedEvent.InputTuple,
      ClaimTimeIntervalChangedEvent.OutputTuple,
      ClaimTimeIntervalChangedEvent.OutputObject
    >;
    ClaimTimeIntervalChanged: TypedContractEvent<
      ClaimTimeIntervalChangedEvent.InputTuple,
      ClaimTimeIntervalChangedEvent.OutputTuple,
      ClaimTimeIntervalChangedEvent.OutputObject
    >;

    "CnChanged(uint256)": TypedContractEvent<
      CnChangedEvent.InputTuple,
      CnChangedEvent.OutputTuple,
      CnChangedEvent.OutputObject
    >;
    CnChanged: TypedContractEvent<
      CnChangedEvent.InputTuple,
      CnChangedEvent.OutputTuple,
      CnChangedEvent.OutputObject
    >;

    "CpChanged(uint256)": TypedContractEvent<
      CpChangedEvent.InputTuple,
      CpChangedEvent.OutputTuple,
      CpChangedEvent.OutputObject
    >;
    CpChanged: TypedContractEvent<
      CpChangedEvent.InputTuple,
      CpChangedEvent.OutputTuple,
      CpChangedEvent.OutputObject
    >;

    "CsChanged(uint256)": TypedContractEvent<
      CsChangedEvent.InputTuple,
      CsChangedEvent.OutputTuple,
      CsChangedEvent.OutputObject
    >;
    CsChanged: TypedContractEvent<
      CsChangedEvent.InputTuple,
      CsChangedEvent.OutputTuple,
      CsChangedEvent.OutputObject
    >;

    "DifferenceBetweenLevelsChanged(uint256)": TypedContractEvent<
      DifferenceBetweenLevelsChangedEvent.InputTuple,
      DifferenceBetweenLevelsChangedEvent.OutputTuple,
      DifferenceBetweenLevelsChangedEvent.OutputObject
    >;
    DifferenceBetweenLevelsChanged: TypedContractEvent<
      DifferenceBetweenLevelsChangedEvent.InputTuple,
      DifferenceBetweenLevelsChangedEvent.OutputTuple,
      DifferenceBetweenLevelsChangedEvent.OutputObject
    >;

    "ExperienceEarnedAfterForageChanged(uint256)": TypedContractEvent<
      ExperienceEarnedAfterForageChangedEvent.InputTuple,
      ExperienceEarnedAfterForageChangedEvent.OutputTuple,
      ExperienceEarnedAfterForageChangedEvent.OutputObject
    >;
    ExperienceEarnedAfterForageChanged: TypedContractEvent<
      ExperienceEarnedAfterForageChangedEvent.InputTuple,
      ExperienceEarnedAfterForageChangedEvent.OutputTuple,
      ExperienceEarnedAfterForageChangedEvent.OutputObject
    >;

    "ExperienceEarnedAfterRaidFailedChanged(uint256)": TypedContractEvent<
      ExperienceEarnedAfterRaidFailedChangedEvent.InputTuple,
      ExperienceEarnedAfterRaidFailedChangedEvent.OutputTuple,
      ExperienceEarnedAfterRaidFailedChangedEvent.OutputObject
    >;
    ExperienceEarnedAfterRaidFailedChanged: TypedContractEvent<
      ExperienceEarnedAfterRaidFailedChangedEvent.InputTuple,
      ExperienceEarnedAfterRaidFailedChangedEvent.OutputTuple,
      ExperienceEarnedAfterRaidFailedChangedEvent.OutputObject
    >;

    "ExperienceEarnedAfterRaidSuccessChanged(uint256)": TypedContractEvent<
      ExperienceEarnedAfterRaidSuccessChangedEvent.InputTuple,
      ExperienceEarnedAfterRaidSuccessChangedEvent.OutputTuple,
      ExperienceEarnedAfterRaidSuccessChangedEvent.OutputObject
    >;
    ExperienceEarnedAfterRaidSuccessChanged: TypedContractEvent<
      ExperienceEarnedAfterRaidSuccessChangedEvent.InputTuple,
      ExperienceEarnedAfterRaidSuccessChangedEvent.OutputTuple,
      ExperienceEarnedAfterRaidSuccessChangedEvent.OutputObject
    >;

    "ExperienceEarnedAfterUpgradeChanged(uint256)": TypedContractEvent<
      ExperienceEarnedAfterUpgradeChangedEvent.InputTuple,
      ExperienceEarnedAfterUpgradeChangedEvent.OutputTuple,
      ExperienceEarnedAfterUpgradeChangedEvent.OutputObject
    >;
    ExperienceEarnedAfterUpgradeChanged: TypedContractEvent<
      ExperienceEarnedAfterUpgradeChangedEvent.InputTuple,
      ExperienceEarnedAfterUpgradeChangedEvent.OutputTuple,
      ExperienceEarnedAfterUpgradeChangedEvent.OutputObject
    >;

    "ForagePercentageChanged(uint256)": TypedContractEvent<
      ForagePercentageChangedEvent.InputTuple,
      ForagePercentageChangedEvent.OutputTuple,
      ForagePercentageChangedEvent.OutputObject
    >;
    ForagePercentageChanged: TypedContractEvent<
      ForagePercentageChangedEvent.InputTuple,
      ForagePercentageChangedEvent.OutputTuple,
      ForagePercentageChangedEvent.OutputObject
    >;

    "HoneyYieldConstantChanged(uint256)": TypedContractEvent<
      HoneyYieldConstantChangedEvent.InputTuple,
      HoneyYieldConstantChangedEvent.OutputTuple,
      HoneyYieldConstantChangedEvent.OutputObject
    >;
    HoneyYieldConstantChanged: TypedContractEvent<
      HoneyYieldConstantChangedEvent.InputTuple,
      HoneyYieldConstantChangedEvent.OutputTuple,
      HoneyYieldConstantChangedEvent.OutputObject
    >;

    "IncentiveEarnAfterRaidChanged(uint256)": TypedContractEvent<
      IncentiveEarnAfterRaidChangedEvent.InputTuple,
      IncentiveEarnAfterRaidChangedEvent.OutputTuple,
      IncentiveEarnAfterRaidChangedEvent.OutputObject
    >;
    IncentiveEarnAfterRaidChanged: TypedContractEvent<
      IncentiveEarnAfterRaidChangedEvent.InputTuple,
      IncentiveEarnAfterRaidChangedEvent.OutputTuple,
      IncentiveEarnAfterRaidChangedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MaxEnergyDeductionValueChanged(uint256)": TypedContractEvent<
      MaxEnergyDeductionValueChangedEvent.InputTuple,
      MaxEnergyDeductionValueChangedEvent.OutputTuple,
      MaxEnergyDeductionValueChangedEvent.OutputObject
    >;
    MaxEnergyDeductionValueChanged: TypedContractEvent<
      MaxEnergyDeductionValueChangedEvent.InputTuple,
      MaxEnergyDeductionValueChangedEvent.OutputTuple,
      MaxEnergyDeductionValueChangedEvent.OutputObject
    >;

    "MaxQueenChanged(uint256)": TypedContractEvent<
      MaxQueenChangedEvent.InputTuple,
      MaxQueenChangedEvent.OutputTuple,
      MaxQueenChangedEvent.OutputObject
    >;
    MaxQueenChanged: TypedContractEvent<
      MaxQueenChangedEvent.InputTuple,
      MaxQueenChangedEvent.OutputTuple,
      MaxQueenChangedEvent.OutputObject
    >;

    "MaxResourcesValueChanged(uint256)": TypedContractEvent<
      MaxResourcesValueChangedEvent.InputTuple,
      MaxResourcesValueChangedEvent.OutputTuple,
      MaxResourcesValueChangedEvent.OutputObject
    >;
    MaxResourcesValueChanged: TypedContractEvent<
      MaxResourcesValueChangedEvent.InputTuple,
      MaxResourcesValueChangedEvent.OutputTuple,
      MaxResourcesValueChangedEvent.OutputObject
    >;

    "MaxWorkerChanged(uint256)": TypedContractEvent<
      MaxWorkerChangedEvent.InputTuple,
      MaxWorkerChangedEvent.OutputTuple,
      MaxWorkerChangedEvent.OutputObject
    >;
    MaxWorkerChanged: TypedContractEvent<
      MaxWorkerChangedEvent.InputTuple,
      MaxWorkerChangedEvent.OutputTuple,
      MaxWorkerChangedEvent.OutputObject
    >;

    "MinEnergyDeductionValueChanged(uint256)": TypedContractEvent<
      MinEnergyDeductionValueChangedEvent.InputTuple,
      MinEnergyDeductionValueChangedEvent.OutputTuple,
      MinEnergyDeductionValueChangedEvent.OutputObject
    >;
    MinEnergyDeductionValueChanged: TypedContractEvent<
      MinEnergyDeductionValueChangedEvent.InputTuple,
      MinEnergyDeductionValueChangedEvent.OutputTuple,
      MinEnergyDeductionValueChangedEvent.OutputObject
    >;

    "MinResourcesValueChanged(uint256)": TypedContractEvent<
      MinResourcesValueChangedEvent.InputTuple,
      MinResourcesValueChangedEvent.OutputTuple,
      MinResourcesValueChangedEvent.OutputObject
    >;
    MinResourcesValueChanged: TypedContractEvent<
      MinResourcesValueChangedEvent.InputTuple,
      MinResourcesValueChangedEvent.OutputTuple,
      MinResourcesValueChangedEvent.OutputObject
    >;

    "NectarRequiredToClaimChanged(uint256)": TypedContractEvent<
      NectarRequiredToClaimChangedEvent.InputTuple,
      NectarRequiredToClaimChangedEvent.OutputTuple,
      NectarRequiredToClaimChangedEvent.OutputObject
    >;
    NectarRequiredToClaimChanged: TypedContractEvent<
      NectarRequiredToClaimChangedEvent.InputTuple,
      NectarRequiredToClaimChangedEvent.OutputTuple,
      NectarRequiredToClaimChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RaidHoneyFeeChanged(uint256)": TypedContractEvent<
      RaidHoneyFeeChangedEvent.InputTuple,
      RaidHoneyFeeChangedEvent.OutputTuple,
      RaidHoneyFeeChangedEvent.OutputObject
    >;
    RaidHoneyFeeChanged: TypedContractEvent<
      RaidHoneyFeeChangedEvent.InputTuple,
      RaidHoneyFeeChangedEvent.OutputTuple,
      RaidHoneyFeeChangedEvent.OutputObject
    >;

    "RaidSapFeeChanged(uint256)": TypedContractEvent<
      RaidSapFeeChangedEvent.InputTuple,
      RaidSapFeeChangedEvent.OutputTuple,
      RaidSapFeeChangedEvent.OutputObject
    >;
    RaidSapFeeChanged: TypedContractEvent<
      RaidSapFeeChangedEvent.InputTuple,
      RaidSapFeeChangedEvent.OutputTuple,
      RaidSapFeeChangedEvent.OutputObject
    >;

    "ResourcesRefreshIntervalChanged(uint256)": TypedContractEvent<
      ResourcesRefreshIntervalChangedEvent.InputTuple,
      ResourcesRefreshIntervalChangedEvent.OutputTuple,
      ResourcesRefreshIntervalChangedEvent.OutputObject
    >;
    ResourcesRefreshIntervalChanged: TypedContractEvent<
      ResourcesRefreshIntervalChangedEvent.InputTuple,
      ResourcesRefreshIntervalChangedEvent.OutputTuple,
      ResourcesRefreshIntervalChangedEvent.OutputObject
    >;
  };
}
