/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HiveManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_DENOMINATOR"
      | "ONE_EPOCH"
      | "beeStatus"
      | "buzzkillAddressProvider"
      | "collectHoney"
      | "createHive"
      | "forage"
      | "getAvailableHoneyInHive"
      | "getHivePoolMultiplier"
      | "getHiveResources"
      | "getUserClaimableHoney"
      | "hives"
      | "initialize"
      | "isBeeInAction"
      | "onERC721Received"
      | "stakeBee"
      | "startRaid"
      | "totalHives"
      | "unstakeBee"
      | "updateHiveDefense"
      | "updateHiveProductivity"
      | "updradeBeeSkills"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollectHoney"
      | "ForageFinished"
      | "HiveCreated"
      | "Initialized"
      | "NFTStaked"
      | "NFTUnstaked"
      | "RaidFinished"
      | "ResourcesCollected"
      | "UpgradeBeeSkillSucceed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ONE_EPOCH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "beeStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buzzkillAddressProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectHoney",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createHive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forage",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableHoneyInHive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHivePoolMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHiveResources",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClaimableHoney",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hives", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBeeInAction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeBee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startRaid",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalHives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeBee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHiveDefense",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHiveProductivity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updradeBeeSkills",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ONE_EPOCH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beeStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buzzkillAddressProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectHoney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createHive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "forage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableHoneyInHive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHivePoolMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHiveResources",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClaimableHoney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hives", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBeeInAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeBee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startRaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalHives", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstakeBee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateHiveDefense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateHiveProductivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updradeBeeSkills",
    data: BytesLike
  ): Result;
}

export namespace CollectHoneyEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    hiveId: BigNumberish,
    honey: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, hiveId: bigint, honey: bigint];
  export interface OutputObject {
    tokenId: bigint;
    hiveId: bigint;
    honey: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForageFinishedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    hiveId: BigNumberish,
    productivityEarned: BigNumberish,
    experienceEarned: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    hiveId: bigint,
    productivityEarned: bigint,
    experienceEarned: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    hiveId: bigint;
    productivityEarned: bigint;
    experienceEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HiveCreatedEvent {
  export type InputTuple = [hiveId: BigNumberish, habitatId: BigNumberish];
  export type OutputTuple = [hiveId: bigint, habitatId: bigint];
  export interface OutputObject {
    hiveId: bigint;
    habitatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTStakedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTUnstakedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaidFinishedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    hiveId: BigNumberish,
    honey: BigNumberish,
    productivityEarned: BigNumberish,
    experienceEarned: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    hiveId: bigint,
    honey: bigint,
    productivityEarned: bigint,
    experienceEarned: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    hiveId: bigint;
    honey: bigint;
    productivityEarned: bigint;
    experienceEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResourcesCollectedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    hiveId: BigNumberish,
    nectarGathered: BigNumberish,
    pollenGathered: BigNumberish,
    sapGathered: BigNumberish,
    sharedNectar: BigNumberish,
    sharedPollen: BigNumberish,
    sharedSap: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    hiveId: bigint,
    nectarGathered: bigint,
    pollenGathered: bigint,
    sapGathered: bigint,
    sharedNectar: bigint,
    sharedPollen: bigint,
    sharedSap: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    hiveId: bigint;
    nectarGathered: bigint;
    pollenGathered: bigint;
    sapGathered: bigint;
    sharedNectar: bigint;
    sharedPollen: bigint;
    sharedSap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeBeeSkillSucceedEvent {
  export type InputTuple = [
    hiveId: BigNumberish,
    tokenId: BigNumberish,
    beeSkills: BigNumberish
  ];
  export type OutputTuple = [
    hiveId: bigint,
    tokenId: bigint,
    beeSkills: bigint
  ];
  export interface OutputObject {
    hiveId: bigint;
    tokenId: bigint;
    beeSkills: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HiveManager extends BaseContract {
  connect(runner?: ContractRunner | null): HiveManager;
  waitForDeployment(): Promise<this>;

  interface: HiveManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  ONE_EPOCH: TypedContractMethod<[], [bigint], "view">;

  beeStatus: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        beeId: bigint;
        beeProductivity: bigint;
        beeWorkIncentive: bigint;
        beeDefense: bigint;
        lastClaimedBlock: bigint;
      }
    ],
    "view"
  >;

  buzzkillAddressProvider: TypedContractMethod<[], [string], "view">;

  collectHoney: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createHive: TypedContractMethod<
    [habitatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forage: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish, _habitatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvailableHoneyInHive: TypedContractMethod<
    [_hiveId: BigNumberish],
    [bigint],
    "view"
  >;

  getHivePoolMultiplier: TypedContractMethod<
    [_hiveId: BigNumberish],
    [bigint],
    "view"
  >;

  getHiveResources: TypedContractMethod<
    [_hiveId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getUserClaimableHoney: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  hives: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        habitatId: bigint;
        numQueens: bigint;
        numWorkers: bigint;
        nectar: bigint;
        pollen: bigint;
        sap: bigint;
        hiveProductivity: bigint;
        hiveDefense: bigint;
        availableHoneyInHive: bigint;
        lastAvailableHoneyUpdateBlock: bigint;
        hiveTotalIncentive: bigint;
        lastBaseIncentiveUpdateBlock: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [_buzzkillAddressProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  isBeeInAction: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  stakeBee: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  startRaid: TypedContractMethod<
    [
      _hiveId: BigNumberish,
      _tokenId: BigNumberish,
      _raidedHiveId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalHives: TypedContractMethod<[], [bigint], "view">;

  unstakeBee: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateHiveDefense: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateHiveProductivity: TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updradeBeeSkills: TypedContractMethod<
    [
      _hiveId: BigNumberish,
      _tokenId: BigNumberish,
      _beeSkill: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ONE_EPOCH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beeStatus"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        beeId: bigint;
        beeProductivity: bigint;
        beeWorkIncentive: bigint;
        beeDefense: bigint;
        lastClaimedBlock: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buzzkillAddressProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectHoney"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createHive"
  ): TypedContractMethod<[habitatId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forage"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish, _habitatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvailableHoneyInHive"
  ): TypedContractMethod<[_hiveId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHivePoolMultiplier"
  ): TypedContractMethod<[_hiveId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHiveResources"
  ): TypedContractMethod<
    [_hiveId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserClaimableHoney"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hives"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        habitatId: bigint;
        numQueens: bigint;
        numWorkers: bigint;
        nectar: bigint;
        pollen: bigint;
        sap: bigint;
        hiveProductivity: bigint;
        hiveDefense: bigint;
        availableHoneyInHive: bigint;
        lastAvailableHoneyUpdateBlock: bigint;
        hiveTotalIncentive: bigint;
        lastBaseIncentiveUpdateBlock: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_buzzkillAddressProvider: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBeeInAction"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeBee"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startRaid"
  ): TypedContractMethod<
    [
      _hiveId: BigNumberish,
      _tokenId: BigNumberish,
      _raidedHiveId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalHives"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unstakeBee"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateHiveDefense"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateHiveProductivity"
  ): TypedContractMethod<
    [_hiveId: BigNumberish, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updradeBeeSkills"
  ): TypedContractMethod<
    [
      _hiveId: BigNumberish,
      _tokenId: BigNumberish,
      _beeSkill: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CollectHoney"
  ): TypedContractEvent<
    CollectHoneyEvent.InputTuple,
    CollectHoneyEvent.OutputTuple,
    CollectHoneyEvent.OutputObject
  >;
  getEvent(
    key: "ForageFinished"
  ): TypedContractEvent<
    ForageFinishedEvent.InputTuple,
    ForageFinishedEvent.OutputTuple,
    ForageFinishedEvent.OutputObject
  >;
  getEvent(
    key: "HiveCreated"
  ): TypedContractEvent<
    HiveCreatedEvent.InputTuple,
    HiveCreatedEvent.OutputTuple,
    HiveCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "NFTStaked"
  ): TypedContractEvent<
    NFTStakedEvent.InputTuple,
    NFTStakedEvent.OutputTuple,
    NFTStakedEvent.OutputObject
  >;
  getEvent(
    key: "NFTUnstaked"
  ): TypedContractEvent<
    NFTUnstakedEvent.InputTuple,
    NFTUnstakedEvent.OutputTuple,
    NFTUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RaidFinished"
  ): TypedContractEvent<
    RaidFinishedEvent.InputTuple,
    RaidFinishedEvent.OutputTuple,
    RaidFinishedEvent.OutputObject
  >;
  getEvent(
    key: "ResourcesCollected"
  ): TypedContractEvent<
    ResourcesCollectedEvent.InputTuple,
    ResourcesCollectedEvent.OutputTuple,
    ResourcesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeBeeSkillSucceed"
  ): TypedContractEvent<
    UpgradeBeeSkillSucceedEvent.InputTuple,
    UpgradeBeeSkillSucceedEvent.OutputTuple,
    UpgradeBeeSkillSucceedEvent.OutputObject
  >;

  filters: {
    "CollectHoney(uint256,uint256,uint256)": TypedContractEvent<
      CollectHoneyEvent.InputTuple,
      CollectHoneyEvent.OutputTuple,
      CollectHoneyEvent.OutputObject
    >;
    CollectHoney: TypedContractEvent<
      CollectHoneyEvent.InputTuple,
      CollectHoneyEvent.OutputTuple,
      CollectHoneyEvent.OutputObject
    >;

    "ForageFinished(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ForageFinishedEvent.InputTuple,
      ForageFinishedEvent.OutputTuple,
      ForageFinishedEvent.OutputObject
    >;
    ForageFinished: TypedContractEvent<
      ForageFinishedEvent.InputTuple,
      ForageFinishedEvent.OutputTuple,
      ForageFinishedEvent.OutputObject
    >;

    "HiveCreated(uint256,uint256)": TypedContractEvent<
      HiveCreatedEvent.InputTuple,
      HiveCreatedEvent.OutputTuple,
      HiveCreatedEvent.OutputObject
    >;
    HiveCreated: TypedContractEvent<
      HiveCreatedEvent.InputTuple,
      HiveCreatedEvent.OutputTuple,
      HiveCreatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "NFTStaked(uint256)": TypedContractEvent<
      NFTStakedEvent.InputTuple,
      NFTStakedEvent.OutputTuple,
      NFTStakedEvent.OutputObject
    >;
    NFTStaked: TypedContractEvent<
      NFTStakedEvent.InputTuple,
      NFTStakedEvent.OutputTuple,
      NFTStakedEvent.OutputObject
    >;

    "NFTUnstaked(uint256)": TypedContractEvent<
      NFTUnstakedEvent.InputTuple,
      NFTUnstakedEvent.OutputTuple,
      NFTUnstakedEvent.OutputObject
    >;
    NFTUnstaked: TypedContractEvent<
      NFTUnstakedEvent.InputTuple,
      NFTUnstakedEvent.OutputTuple,
      NFTUnstakedEvent.OutputObject
    >;

    "RaidFinished(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RaidFinishedEvent.InputTuple,
      RaidFinishedEvent.OutputTuple,
      RaidFinishedEvent.OutputObject
    >;
    RaidFinished: TypedContractEvent<
      RaidFinishedEvent.InputTuple,
      RaidFinishedEvent.OutputTuple,
      RaidFinishedEvent.OutputObject
    >;

    "ResourcesCollected(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ResourcesCollectedEvent.InputTuple,
      ResourcesCollectedEvent.OutputTuple,
      ResourcesCollectedEvent.OutputObject
    >;
    ResourcesCollected: TypedContractEvent<
      ResourcesCollectedEvent.InputTuple,
      ResourcesCollectedEvent.OutputTuple,
      ResourcesCollectedEvent.OutputObject
    >;

    "UpgradeBeeSkillSucceed(uint256,uint256,uint8)": TypedContractEvent<
      UpgradeBeeSkillSucceedEvent.InputTuple,
      UpgradeBeeSkillSucceedEvent.OutputTuple,
      UpgradeBeeSkillSucceedEvent.OutputObject
    >;
    UpgradeBeeSkillSucceed: TypedContractEvent<
      UpgradeBeeSkillSucceedEvent.InputTuple,
      UpgradeBeeSkillSucceedEvent.OutputTuple,
      UpgradeBeeSkillSucceedEvent.OutputObject
    >;
  };
}
