/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as openzeppelin from "./@openzeppelin";
export * as vrc25 from "./@vrc25";
export * as vrc725 from "./@vrc725";
export * as contracts from "./contracts";
export * as interfaces from "./interfaces";
