/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Controllable,
  ControllableInterface,
} from "../../../contracts/helper/Controllable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isController",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Controllable__factory {
  static readonly abi = _abi;
  static createInterface(): ControllableInterface {
    return new Interface(_abi) as ControllableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Controllable {
    return new Contract(address, _abi, runner) as unknown as Controllable;
  }
}
