/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IBuzzkillAddressProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buzzkillNFTAddress"
      | "gameConfigAddress"
      | "hiveManagerAddress"
      | "honeyAddress"
      | "honeyDistributionAddress"
      | "worldMapAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buzzkillNFTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gameConfigAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hiveManagerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "honeyAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "honeyDistributionAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "worldMapAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "buzzkillNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameConfigAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hiveManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "honeyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "honeyDistributionAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "worldMapAddress",
    data: BytesLike
  ): Result;
}

export interface IBuzzkillAddressProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IBuzzkillAddressProvider;
  waitForDeployment(): Promise<this>;

  interface: IBuzzkillAddressProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buzzkillNFTAddress: TypedContractMethod<[], [string], "view">;

  gameConfigAddress: TypedContractMethod<[], [string], "view">;

  hiveManagerAddress: TypedContractMethod<[], [string], "view">;

  honeyAddress: TypedContractMethod<[], [string], "view">;

  honeyDistributionAddress: TypedContractMethod<[], [string], "view">;

  worldMapAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buzzkillNFTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gameConfigAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hiveManagerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "honeyAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "honeyDistributionAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "worldMapAddress"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
