/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBuzzkillAddressProvider } from "./IBuzzkillAddressProvider";
export type { IBuzzkillNFT } from "./IBuzzkillNFT";
export type { IGameConfig } from "./IGameConfig";
export type { IHive } from "./IHive";
export type { IHoney } from "./IHoney";
export type { IHoneyDistribution } from "./IHoneyDistribution";
export type { IWorldMap } from "./IWorldMap";
