/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IWorldMapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentHabitatId"
      | "forage"
      | "getAmountEnergyDeductionAfterForage"
      | "getAmountIncentiveEarnAfterForage"
      | "getHabitat"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "currentHabitatId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountEnergyDeductionAfterForage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountIncentiveEarnAfterForage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHabitat",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentHabitatId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAmountEnergyDeductionAfterForage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountIncentiveEarnAfterForage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHabitat", data: BytesLike): Result;
}

export interface IWorldMap extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldMap;
  waitForDeployment(): Promise<this>;

  interface: IWorldMapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentHabitatId: TypedContractMethod<[], [bigint], "view">;

  forage: TypedContractMethod<
    [tokenId: BigNumberish, habitatId: BigNumberish],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;

  getAmountEnergyDeductionAfterForage: TypedContractMethod<
    [habitatId: BigNumberish],
    [bigint],
    "view"
  >;

  getAmountIncentiveEarnAfterForage: TypedContractMethod<
    [habitatId: BigNumberish],
    [bigint],
    "view"
  >;

  getHabitat: TypedContractMethod<
    [habitatId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentHabitatId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, habitatId: BigNumberish],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAmountEnergyDeductionAfterForage"
  ): TypedContractMethod<[habitatId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAmountIncentiveEarnAfterForage"
  ): TypedContractMethod<[habitatId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHabitat"
  ): TypedContractMethod<
    [habitatId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  filters: {};
}
